# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attack_analysis_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionTCP_SYN_Flood = QtWidgets.QAction(MainWindow)
        self.actionTCP_SYN_Flood.setObjectName("actionTCP_SYN_Flood")
        self.actionHTTP_Flood = QtWidgets.QAction(MainWindow)
        self.actionHTTP_Flood.setObjectName("actionHTTP_Flood")
        self.actionTCPSYN = QtWidgets.QAction(MainWindow)
        self.actionTCPSYN.setObjectName("actionTCPSYN")
        self.actionTCPscan = QtWidgets.QAction(MainWindow)
        self.actionTCPscan.setObjectName("actionTCPscan")
        self.actionDOS = QtWidgets.QAction(MainWindow)
        self.actionDOS.setObjectName("actionDOS")
        self.actionARP = QtWidgets.QAction(MainWindow)
        self.actionARP.setObjectName("actionARP")
        self.actionARPPoi = QtWidgets.QAction(MainWindow)
        self.actionARPPoi.setObjectName("actionARPPoi")
        self.actionICMP = QtWidgets.QAction(MainWindow)
        self.actionICMP.setObjectName("actionICMP")
        self.actionDNS = QtWidgets.QAction(MainWindow)
        self.actionDNS.setObjectName("actionDNS")
        self.actionrunAll = QtWidgets.QAction(MainWindow)
        self.actionrunAll.setObjectName("actionrunALL")
        self.actionFlagged = QtWidgets.QAction(MainWindow)
        self.actionFlagged.setObjectName("actionFlagged")
        self.toolBar.addAction(self.actionTCPSYN)
        self.toolBar.addAction(self.actionTCPscan)
        self.toolBar.addAction(self.actionDOS)
        self.toolBar.addAction(self.actionARPPoi)
        self.toolBar.addAction(self.actionICMP)
        self.toolBar.addAction(self.actionHTTP_Flood)
        self.toolBar.addAction(self.actionDNS)
        self.toolBar.addAction(self.actionrunAll)
        self.toolBar.addAction(self.actionFlagged)


        spacer = QtWidgets.QWidget(MainWindow)
        spacer.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)


        self.threshold_input = QtWidgets.QLineEdit(MainWindow)
        self.threshold_input.setObjectName("threshold_input")
        self.threshold_input.setFixedWidth(60)
        self.threshold_input.setFixedHeight(21)
        onlyInt = QtGui.QIntValidator()
        self.threshold_input.setValidator(onlyInt)
        self.threshold_label = QtWidgets.QLabel("Threshold:")

        self.toolBar.addSeparator()
        self.toolBar.addWidget(spacer)
        self.toolBar.addWidget(self.threshold_label)
        self.toolBar.addWidget(self.threshold_input)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attack Analysis"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

        self.actionTCPSYN.setText(_translate("MainWindow", "TCP SYN Flood"))
        self.actionTCPscan.setText(_translate("MainWindow", "TCP Connection Scanning"))
        self.actionDOS.setText(_translate("MainWindow", "DOS"))
        self.actionARPPoi.setText(_translate("MainWindow", "ARP Poison"))
        self.actionICMP.setText(_translate("MainWindow", "ICMP Flood"))
        self.actionHTTP_Flood.setText(_translate("MainWindow", "HTTP Flood"))
        self.actionDNS.setText(_translate("MainWindow", "DNS Flood"))
        self.actionrunAll.setText(_translate("MainWindow", "Run all tests"))
        self.actionFlagged.setText(_translate("MainWindow", "Flagged Addr"))
