# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionProtocol = QtWidgets.QAction(MainWindow)
        self.actionProtocol.setObjectName("actionProtocol")
        self.actionIPv4Network = QtWidgets.QAction(MainWindow)
        self.actionIPv4Network.setObjectName("actionIPv4Network")
        self.actionIPv6Network = QtWidgets.QAction(MainWindow)
        self.actionIPv6Network.setObjectName("actionIPv6")
        self.actionMACNetwork = QtWidgets.QAction(MainWindow)
        self.actionMACNetwork.setObjectName("actionMACNetwork")
        self.actionSource = QtWidgets.QAction(MainWindow)
        self.actionSource.setObjectName("actionSource")
        self.actionDest = QtWidgets.QAction(MainWindow)
        self.actionDest.setObjectName("actionDest")
        self.toolBar.addAction(self.actionProtocol)
        self.toolBar.addAction(self.actionIPv4Network)
        self.toolBar.addAction(self.actionIPv6Network)
        self.toolBar.addAction(self.actionMACNetwork)
        self.toolBar.addAction(self.actionSource)
        self.toolBar.addAction(self.actionDest)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analysis Graphs"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionProtocol.setText(_translate("MainWindow", "Protocol"))
        self.actionProtocol.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\">Protocol Frequency</p></body></html>"))
        self.actionIPv4Network.setText(_translate("MainWindow", "IPv4 Network"))
        self.actionIPv6Network.setText(_translate("MainWindow", "IPv6 Network"))
        self.actionMACNetwork.setText(_translate("MainWindow", "MAC Network"))
        self.actionSource.setText(_translate("MainWindow", "Source Frequency"))
        self.actionDest.setText(_translate("MainWindow", "Destination Frequency"))
