# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.info = QtWidgets.QTreeWidget(self.centralwidget)
        self.info.setObjectName("info")
        self.info.headerItem().setText(0, "1")
        self.info.header().setVisible(False)
        self.gridLayout.addWidget(self.info, 0, 0, 1, 2)
        self.data = QtWidgets.QTableWidget(self.centralwidget)
        self.data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.data.setShowGrid(False)
        self.data.setColumnCount(16)
        self.data.setObjectName("data")
        self.data.setRowCount(0)
        self.gridLayout.addWidget(self.data, 1, 0, 1, 1)
        self.fig = QtWidgets.QTableWidget(self.centralwidget)
        self.fig.setShowGrid(False)
        self.fig.setColumnCount(16)
        self.fig.setObjectName("fig")
        self.fig.setRowCount(0)
        self.gridLayout.addWidget(self.fig, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
